/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CompraData;
import AccesoADatos.DetalleCompraData;
import AccesoADatos.ProductoData;
import AccesoADatos.ProveedorData;
import Entidades.Compra;
import Entidades.DetalleCompra;
import Entidades.Producto;
import Entidades.Proveedor;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentino
 */
public class DetalleComprasView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleComprasView
     */
    ProveedorData provData;
    DetalleCompraData detCompData;
    ProductoData prodData;
    CompraData compData;
    DefaultTableModel modelo;
    DefaultTableModel modeloDet;
    
    public DetalleComprasView() {
        initComponents();
        provData = new ProveedorData();
        compData = new CompraData();
        detCompData = new DetalleCompraData();
        prodData = new ProductoData();
        modelo = new DefaultTableModel();
        modeloDet = new DefaultTableModel();
        cargarCombo();
        armarTablaCompras();
        armarTablaDetalles();
        int x = (int) (160/2);
        int y = (int) (15 / 2);
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jDateDesde = new com.toedter.calendar.JDateChooser();
        jDateHasta = new com.toedter.calendar.JDateChooser();
        comboProveedores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDetalles = new javax.swing.JTable();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonVerDetalle = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboProveedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProveedoresItemStateChanged(evt);
            }
        });

        jLabel1.setText("DETALLES DE COMPRAS");

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCompras);

        jTableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableDetalles);

        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Compras");

        jLabel3.setText("Detalles");

        jButtonVerDetalle.setText("Ver Detalle");
        jButtonVerDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(197, 197, 197))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboProveedores, 0, 146, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVerDetalle)
                        .addGap(171, 171, 171))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(comboProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboProveedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProveedoresItemStateChanged
        limpiarRowsCompras();
        limpiarRowsDetalles();
        int id = obtenerIdProveedor();
        Proveedor prov = provData.obtenerProveedorPorId(id);
        List<Compra> compras = compData.obtenerComprasPorProveedor(prov);
        cargarComprasATablaCompras(filtrarCompras(compras));
    }//GEN-LAST:event_comboProveedoresItemStateChanged

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVerDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerDetalleActionPerformed
        limpiarRowsDetalles();
        int row = jTableCompras.getSelectedRow();
        int col = 0; //Es 0 porque ID esta en la primera Columna
        if(row != -1){
            Object idCompra = (jTableCompras.getModel().getValueAt(row, col)); 
            Compra compra = compData.obtenerCompraPorId(Integer.parseInt(idCompra.toString()));
            List<DetalleCompra> detCompras = detCompData.buscarDetallePorCompra(compra);
            cargarDetallesATablaDetalles(detCompras);
        }
    }//GEN-LAST:event_jButtonVerDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void cargarCombo(){
        List<Proveedor> proveedores = provData.obtenerProveedores();
        for(Proveedor prov:proveedores){
            comboProveedores.addItem(prov.getRazonSocial()+" ID:"+prov.getIdProveedor());
        }
    }
    
    int obtenerIdProveedor(){
        String proveedor = comboProveedores.getSelectedItem().toString();
        int id = Integer.parseInt(proveedor.substring(proveedor.lastIndexOf(":") + 1)); 
        return id;
    }
    
    void armarTablaCompras(){
        modelo.setColumnCount(0);
        modelo.addColumn("ID compra");
        modelo.addColumn("Fecha");
        jTableCompras.setModel(modelo);
    }
    
    void armarTablaDetalles(){
        modeloDet.setColumnCount(0);
        modeloDet.addColumn("Cantidad");
        modeloDet.addColumn("Precio");
        modeloDet.addColumn("Producto");
        jTableDetalles.setModel(modeloDet);
    }
    
    void limpiarRowsCompras(){
        modelo.setRowCount(0);
        jTableCompras.setModel(modelo);
    }
    
    void limpiarRowsDetalles(){
        modeloDet.setRowCount(0);
        jTableDetalles.setModel(modeloDet);
    }
    
    void cargarComprasATablaCompras(List<Compra> compras){
        for (Compra comp:compras){
            modelo.addRow(new Object[]{comp.getIdCompra(), comp.getFecha()});
        }
        jTableCompras.setModel(modelo);
    }
    void cargarDetallesATablaDetalles(List<DetalleCompra> detalles){
        for (DetalleCompra det:detalles){
            modeloDet.addRow(new Object[]{det.getCantidad(),
                det.getPrecioCosto(),
                det.getProducto().getNombreProducto()});
        }
        jTableDetalles.setModel(modeloDet);
    }
    
    private List<Compra> filtrarCompras(List<Compra> compras){
        List<Compra> comprasFiltradas = new ArrayList<Compra>();
        boolean desdeEsNulo = false;
        boolean hastaEsNulo = false;
        Date fechaDesde = jDateDesde.getDate();
        Date fechaHasta = jDateHasta.getDate();
        
        
        if (fechaDesde==null){
            desdeEsNulo = true;
        }
        
        if(fechaHasta==null){
            hastaEsNulo = true;
        }
        
        if(desdeEsNulo && hastaEsNulo){
            return compras;
            
        }else if(!desdeEsNulo && hastaEsNulo){
            for(Compra comp:compras){
                 Date date = Date.from(comp.getFecha().atStartOfDay(ZoneId.systemDefault()).toInstant());
                 if(date.equals(fechaDesde) || date.after(fechaDesde)){
                     comprasFiltradas.add(comp);
                 }
            }
            return comprasFiltradas;
            
        }else if(desdeEsNulo && !hastaEsNulo){
            for(Compra comp:compras){
                 Date date = Date.from(comp.getFecha().atStartOfDay(ZoneId.systemDefault()).toInstant());
                 if(date.equals(fechaHasta) || date.before(fechaHasta)){
                     comprasFiltradas.add(comp);
                 }
            }
            return comprasFiltradas;
            
        }else if(!desdeEsNulo && !hastaEsNulo){
            for(Compra comp:compras){
                 Date date = Date.from(comp.getFecha().atStartOfDay(ZoneId.systemDefault()).toInstant());
                 if ((date.equals(fechaHasta) || date.before(fechaHasta)) &&
                    (date.equals(fechaDesde) || date.after(fechaDesde))) {
                     comprasFiltradas.add(comp);
                    }
            }
            return comprasFiltradas;
            
        }else{
            return null; // es imposible esto pero bueno jeje
        }
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboProveedores;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerDetalle;
    private com.toedter.calendar.JDateChooser jDateDesde;
    private com.toedter.calendar.JDateChooser jDateHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JTable jTableDetalles;
    // End of variables declaration//GEN-END:variables
}
